### ISSUE TITLE
Contributor data for the CLDF dataset should be read from CONTRIBUTORS.md

### ISSUE THREAD

**Issue by xrotwang** [intercontinental-dictionary-series/cosgrovevoro#2]
This https://github.com/intercontinental-dictionary-series/cosgrovevoro/blob/894cde9e4606e6ebb64f5327cc1635e3f1694d59/lexibank_cosgrovevoro.py#L25 should be adapted.

See `pylexibank.Dataset.get_creators_and_contributors`.

**Comment by Bibiko** [comment]
done with the help of the new idspy
